"""Синхронизация базы данных

Revision ID: 29ebd97ff398
Revises: 791f31754af5
Create Date: 2024-07-25 14:53:02.470122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29ebd97ff398'
down_revision = '791f31754af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promocode_id', sa.String(length=20), nullable=True))
        batch_op.drop_column('promocodes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promocodes', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('promocode_id')

    # ### end Alembic commands ###
