"""Синхронизация базы данных

Revision ID: 791f31754af5
Revises: 0709c6b72dbd
Create Date: 2024-07-25 14:52:48.342393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '791f31754af5'
down_revision = '0709c6b72dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promocodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('promocodes',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('promocodes',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('promocodes', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
